name: Clojure CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: lein deps
    - name: clj-kondo
      uses: adriffaud/lint-clojure@v1.1.1
    - name: Check formatting
      run: lein cljfmt check
    - name: Check syntax
      run: lein check
    - name: Run tests
      run: lein test
